Update README.md
PathwayCommons/pathway-abstract-classifier pull request #13
Opened 2022-04-17 01:01 UTC by Steven-Palayew

Addresses #12

2022-04-17 03:00 UTC, JohnGiorgi requested changes

2022-04-17 03:00 UTC, JohnGiorgi commented on README.md
> +ktrain may throw a UserWarning which you can safely ignore.
Would make this a comment in the code snippet, ideally right above the line that causes the warning

2022-04-18 18:55 UTC, Steven-Palayew commented
@JohnGiorgi recent commit should address points you brought up here as well as final suggestion in #11 . Lmk what you think!

2022-04-18 20:23 UTC, JohnGiorgi approved these changes

2022-04-18 20:25 UTC, JohnGiorgi commented
Cool, LGTM! I would write the tutorial notebook to follow the installation instructions of the readme rather than just pip install packages directly, but feel free to do that in another PR.

2022-04-18 21:01 UTC, merged